# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']

  - repo: https://github.com/crate-ci/typos
    rev: v1.42.0
    hooks:
      - id: typos
        args: ['--config', '.typos.toml']

  - repo: https://github.com/pre-commit/mirrors-rustfmt
    rev: v2.2.0
    hooks:
      - id: rustfmt
        args: ['--check', '--edition', '2021']

  - repo: https://github.com/rust-lang/rust-clippy
    rev: v0.1.92
    hooks:
      - id: clippy
        args: ['--all-targets', '--all-features', '--', '-D', 'warnings']
